id = "kestral-theme-dark"
name = "Kestral Theme"
version = "0.0.1"
schema_version = 1
authors = ["EvickaStudio <me@evicka.de>"]
description = "Kestral Theme for Zed"
repository = "https://github.com/EvickaStudio/kestral-theme.zed"
